"""Generate  enriched reference model markdown via Claude API."""
import logging
logging.getLogger("research_toolkit").setLevel(logging.ERROR)

from research_toolkit.diligence import Classification, generate_reference

c = Classification(
    customer_type="b2b",
    sector="enterprise_software",
    industry="vertical_saas",
)

ref = generate_reference(
    c,
    enrich=True,
    enrichment_provider="anthropic",
    company_name="",
    company_url="https://.com",
)

meta = ref.metadata
derived = meta.get("classification_derived_fields", {})

lines = []
lines.append("#  — Enriched Reference Model (Claude)")
lines.append("")
lines.append("> Generated by `generate_reference()` with `enrich=True`")
lines.append(f'> **Provider:** {meta.get("enrichment_provider")} / {meta.get("enrichment_model")}')
lines.append(f'> **Elapsed:** {meta.get("enrichment_elapsed_seconds", 0):.1f}s')
lines.append(f'> **Sources:** LLM knowledge, web fetch ({", ".join(meta.get("urls_fetched", []))})')
lines.append("")
lines.append("---")
lines.append("")

lines.append("## Input Classification")
lines.append("")
lines.append("Minimal input — only 3 fields provided:")
lines.append("")
lines.append("| Field | Value |")
lines.append("| ----- | ----- |")
lines.append("| customer_type | b2b |")
lines.append("| sector | enterprise_software |")
lines.append("| industry | vertical_saas |")
lines.append("")

lines.append("## Derived Classification")
lines.append("")
lines.append("Fields derived from research evidence (LLM knowledge + web scrape):")
lines.append("")
lines.append("| Field | Derived Value |")
lines.append("| ----- | ------------- |")
for k, v in derived.items():
    lines.append(f"| {k} | `{v}` |")
lines.append("")
lines.append("---")
lines.append("")

lines.append("## Predicted System Mix")
lines.append("")
if ref.system_mix:
    lines.append("| System Type | Weight |")
    lines.append("| ----------- | ------ |")
    for st, weight in sorted(
        ref.system_mix.__dict__.items(),
        key=lambda x: -x[1] if isinstance(x[1], (int, float)) else 0,
    ):
        if isinstance(weight, (int, float)) and weight > 0:
            lines.append(f"| {st} | {weight:.0%} |")
lines.append("")
lines.append("---")
lines.append("")

lines.append(f"## Domain Contexts ({len(ref.domain_contexts)})")
lines.append("")
for ctx in ref.domain_contexts:
    ent_names = [e.name for e in ctx.entities]
    lines.append(f"### {ctx.name} ({ctx.domain_type.value.upper()})")
    lines.append("")
    if ctx.rationale:
        lines.append(f"> {ctx.rationale}")
        lines.append("")
    if ctx.aggregate_root:
        lines.append(f"**Aggregate Root:** {ctx.aggregate_root}")
        lines.append("")
    lines.append(f"**Entities:** {', '.join(ent_names)}")
    lines.append("")

lines.append("---")
lines.append("")

static = [e for e in ref.entities if e.framework_source != "llm-enrichment"]
llm_ents = [e for e in ref.entities if e.framework_source == "llm-enrichment"]

lines.append(f"## Entities ({len(ref.entities)} total)")
lines.append("")
lines.append(f"**Static:** {len(static)} from framework lookups | **LLM:** {len(llm_ents)} vertical-specific")
lines.append("")

if llm_ents:
    lines.append("### LLM-Generated Vertical Entities")
    lines.append("")
    lines.append("| Entity | Category | Confidence | Domain Type |")
    lines.append("| ------ | -------- | ---------- | ----------- |")
    for e in llm_ents:
        lines.append(f"| {e.name} | {e.category} | {e.confidence:.2f} | {e.domain_type.value} |")
    lines.append("")

lines.append("### Static Entities (framework-predicted)")
lines.append("")
lines.append("| Entity | Category | Source | Domain Type |")
lines.append("| ------ | -------- | ------ | ----------- |")
for e in static:
    lines.append(f"| {e.name} | {e.category} | {e.framework_source} | {e.domain_type.value} |")
lines.append("")
lines.append("---")
lines.append("")

if ref.processes:
    lines.append(f"## Predicted Processes ({len(ref.processes)})")
    lines.append("")
    lines.append("| Process | PCF Category | Framework |")
    lines.append("| ------- | ------------ | --------- |")
    for p in ref.processes:
        lines.append(f"| {p.name} | {p.pcf_category} | {p.framework_source} |")
    lines.append("")
    lines.append("---")
    lines.append("")

if ref.capabilities:
    lines.append(f"## Capability Expectations ({len(ref.capabilities)})")
    lines.append("")
    lines.append("| Component | Expected Maturity | Framework |")
    lines.append("| --------- | ----------------- | --------- |")
    for cap in ref.capabilities:
        lines.append(f"| {cap.component} | {cap.expected_maturity} | {cap.framework_source} |")
    lines.append("")
    lines.append("---")
    lines.append("")

if ref.analytics:
    lines.append(f"## Analytics Expectations ({len(ref.analytics)})")
    lines.append("")
    for a in ref.analytics:
        lines.append(f"### {a.function.title()}")
        lines.append("")
        if a.table_stakes:
            lines.append(f"**Table Stakes:** {', '.join(a.table_stakes)}")
        if a.mature:
            lines.append(f"**Mature:** {', '.join(a.mature)}")
        if a.red_flag_if_missing:
            lines.append(f"**Red Flag if Missing:** {', '.join(a.red_flag_if_missing)}")
        lines.append("")
    lines.append("---")
    lines.append("")

if ref.neutral_capabilities:
    lines.append(f"## Neutral Capabilities ({len(ref.neutral_capabilities)})")
    lines.append("")
    lines.append("| Capability | Expected Complexity | At Scale? | Framework |")
    lines.append("| ---------- | ------------------- | --------- | --------- |")
    for nc in ref.neutral_capabilities:
        lines.append(
            f"| {nc.capability} | {nc.expected_complexity} "
            f"| {'Yes' if nc.expected_at_scale else 'No'} | {nc.framework_source} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")

if ref.team:
    lines.append("## Team Expectations")
    lines.append("")
    lines.append(f"**Expected Headcount:** {ref.team.expected_headcount}")
    if ref.team.expected_roles:
        lines.append(f"**Roles:** {', '.join(ref.team.expected_roles)}")
    if ref.team.signal_if_missing:
        lines.append(f"**Signal if Missing:** {ref.team.signal_if_missing}")
    lines.append("")

print("\n".join(lines))
